### ISSUE TITLE
JWT Documentation Missing

### ISSUE THREAD

**Issue by jonathanlmarsh** [callstats-io/callstats-android#4]
I am trying to add Callstats to our application but am getting stuck making the Callstats object. The constructor lists it requires a JWT, but where is the JWT from? Do I make it? Do I get it from the Callstats? It seems like some detail here is missing.

**Comment by vr000m** [comment]
https://callstats-io.zendesk.com/hc/en-us/articles/115001203329-What-is-Third-Party-Authentication-Using-JWT-Tokens-
